"I don't remember that in the original specification." - 🤷

diff --git a/.bin/backup-python b/.bin/backup-python
--- a/.bin/backup-python
+++ b/.bin/backup-python
@@ -1,10 +1,13 @@
 #!/usr/bin/env bash
 
 # shellcheck source=/dev/null
-source "$HOME/.bash_colors"
+source "$HOME/.config/bash/colors"
 
 # shellcheck source=/dev/null
 source "$HOME/.bin/platform-versions"
+
+OUTPUT_FILE="$HOME/.platform-dependencies/python-$PYTHON_VERSION"
+OUTPUT_FILE_BROAD="$HOME/.platform-dependencies/python"
 
 # # Check if pyenv is managing things
 # if [[ -z "$PYENV_ROOT" ]]; then
@@ -12,24 +15,21 @@ source "$HOME/.bin/platform-versions"
 #     exit
 # fi
 
-OUTPUT_FILE="$HOME/.platform-dependencies/python-$PYTHON_VERSION"
-OUTPUT_FILE_BROAD="$HOME/.platform-dependencies/python"
-
 # Check for pip
-command -v pip &> /dev/null || {
-    echo "${RED}Could not find pip. Stopping.${STOP}"
-    exit
+command -v pip &>/dev/null || {
+  echo "${RED}Could not find pip. Stopping.${STOP}"
+  exit
 }
 
 # Make an empty output file
 # `truncate` not found on fucking macOS
-echo "" > "$OUTPUT_FILE"
+echo "" >"$OUTPUT_FILE"
 
 # Finally write dependencies
 echo "Writing ${CYAN}${OUTPUT_FILE}${STOP}"
 echo "Writing ${CYAN}${OUTPUT_FILE_BROAD}${STOP}"
 
 DEPENDENCIES="$(pip freeze)"
-echo "$DEPENDENCIES" > "$OUTPUT_FILE"
+echo "$DEPENDENCIES" >"$OUTPUT_FILE"
 cp "$OUTPUT_FILE" "$OUTPUT_FILE_BROAD"
 echo "Done"
